export * as star from "./star.svg";
export * as logo from "./logo.svg";
export * as arrowLeft from "./arrowLeft.svg";
export * as character from "./character.svg";
export * as character2 from "./character2.png";
export * as noise from "./noise.png";
export * as buttonBackground from "./buttonbackground.svg";
export * as buttonArrow from "./buttonarrow.svg";
export * as footerLogo from "./footerLogo.svg";
